### ISSUE TITLE
Questions about the DTU fusion 

### ISSUE THREAD

**Issue by Warrior456** [doubleZ0108/GeoMVSNet#20]
Thank you for your great work. I noticed that you provide three fusion methods for the dtu dataset, and it has some impact on the final performance. What I want to ask is which fusion method should I choose when compared to other methods?

**Comment by doubleZ0108** [comment]
In MVSNet, they use `gipuma` (fusibile) for depth maps fusion, and several following works also chose it. However, with the development of the MVS networks, the path of different approaches begins to diverge. So your problem is hard to answer, but if you want a SOTA performance, you can try `open3d` method as we use a modern library for implementation.
