### ISSUE TITLE
Low quality

### ISSUE THREAD

**Issue by cdcseacave** [doubleZ0108/GeoMVSNet#23]
I'm trying to reproduce the results in the paper, following your instructions, your code and your pre-trained model, but the quality of the depth-maps and fused point clouds are far from what is displayed in the paper. What might be the problem? Did you use a different training procedure? Can you share the model you used for testing and how did you train it?

<img width="647" alt="image" src="https://github.com/doubleZ0108/GeoMVSNet/assets/2802670/da8a2778-6a40-4770-bffc-5845e5ef55b3">

**Comment by doubleZ0108** [comment]
The visual results on the T&T dataset are trained on the DTU dataset first and fine-tuned on the BlendedMVS dataset. We release the model pre-trained on the DTU dataset which only contains small objects (far from large scenarios on T&T). Since our original model on BlendedMVS is broken, you may fine-tune the model yourself to reproduce the results.

**Comment by doubleZ0108** [comment]
Also, the fusion parameters when fuse depths into point clouds should be tuned. You can check the code in `fusion` folder.
